management.endpoint.shutdown.enabled: true
management.endpoint.metrics.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoints.web.exposure.exclude: beans

logging.level.io.github.oxnz.Ingrid: DEBUG

tx.http.executor:
  timeoutMS: 1000
  maxConn: 200
  maxConnPerRoute: 8
  keepAliveMS: 30000
  workerCount: 8
